# Generated by Django 4.1.3 on 2022-12-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("photo_url", models.CharField(max_length=300)),
                ("tags", models.CharField(max_length=20)),
                ("github_url", models.CharField(max_length=300)),
            ],
        ),
    ]
