# Generated by Django 4.1.3 on 2022-12-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default="DESCRIPTION"),
            preserve_default=False,
        ),
    ]
