# Generated by Django 4.1.3 on 2022-12-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0002_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.CharField(max_length=100),
        ),
    ]
